/**
 * Real-length fixtures (20-30 pages as PDF). Each is written as markdown:
 *   "## N. Title" for clauses, "N.M text" paragraphs for sub-clauses,
 *   "# Schedule N: Title" for schedules (numbering restarts), and pipe tables.
 * The long PDF renderer adds a table of contents, running headers and page footers.
 */

const COMPANY =
  "Northwind Analytics sp. z o.o., a limited liability company with its registered office at ul. Prosta 51, 00-838 Warsaw, Poland, entered in the register of entrepreneurs under KRS number 0000712345";

type Clause = [title: string, subclauses: string[]];

function clauses(list: Clause[], start = 1): string {
  return list
    .map(([title, subs], i) => {
      const n = start + i;
      return [`## ${n}. ${title}`, ...subs.map((s, j) => `${n}.${j + 1} ${s}`)].join("\n\n");
    })
    .join("\n\n");
}

function schedule(n: number, title: string, body: string): string {
  return `# Schedule ${n}: ${title}\n\n${body}`;
}

function scheduleClauses(n: number, subs: string[]): string {
  return subs.map((s, j) => `${n}.${j + 1} ${s}`).join("\n\n");
}

function table(header: string[], rows: string[][]): string {
  return [`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`, ...rows.map((r) => `| ${r.join(" | ")} |`)].join("\n");
}

// ---------------------------------------------------------------------------
// Shared general clauses. `sup` is the counterparty's defined term.
// ---------------------------------------------------------------------------

const definitions = (sup: string, extra: string[]): Clause => [
  "Definitions and interpretation",
  [
    `In this Agreement the following words and expressions have the meanings given below unless the context requires otherwise.`,
    `"Affiliate" means, in relation to a party, any entity that directly or indirectly controls, is controlled by, or is under common control with that party, where "control" means ownership of more than fifty per cent of the voting rights or the power to direct management and policies.`,
    `"Applicable Law" means all laws, regulations, binding codes of practice and requirements of any regulatory body that apply to a party or to the performance of its obligations under this Agreement from time to time.`,
    `"Business Day" means a day other than a Saturday, Sunday or public holiday in Poland on which banks in Warsaw are open for general business.`,
    `"Charges" means the charges payable by the Company to the ${sup} as set out in the pricing schedule, as varied from time to time in accordance with the change control procedure.`,
    `"Company Data" means all data, including Personal Data, supplied by or on behalf of the Company or generated by the ${sup} in the course of providing the services, together with any data derived from such data.`,
    `"Confidential Information" means all information of a confidential nature disclosed by or on behalf of a party, whether before or after the Effective Date, in any form or medium, including information relating to the disclosing party's business, customers, finances, technology, products, know-how and trade secrets.`,
    `"Data Protection Legislation" means Regulation (EU) 2016/679 (the GDPR), the Polish Act of 10 May 2018 on the protection of personal data, and all other Applicable Law relating to the processing of personal data and privacy.`,
    `"Effective Date" means the date on which this Agreement has been signed by both parties.`,
    `"Good Industry Practice" means the exercise of the degree of skill, care, prudence, efficiency, foresight and timeliness that would reasonably be expected from a leading supplier of services similar to the services under this Agreement.`,
    `"Intellectual Property Rights" means patents, rights to inventions, copyright and related rights, trade marks, business names, domain names, rights in get-up, goodwill, rights in designs, rights in computer software, database rights, rights to preserve the confidentiality of information and all other intellectual property rights, in each case whether registered or unregistered, in any part of the world.`,
    `"Personal Data", "Controller", "Processor", "Data Subject" and "Processing" have the meanings given to them in the Data Protection Legislation.`,
    `"Security Incident" means any actual or reasonably suspected unauthorised access to, or loss, disclosure, alteration or destruction of, Company Data.`,
    ...extra,
    `Clause, schedule and paragraph headings do not affect the interpretation of this Agreement. The schedules form part of this Agreement and have effect as if set out in full in its body. A reference to this Agreement includes the schedules.`,
    `Words in the singular include the plural and vice versa. A reference to a statute or statutory provision is a reference to it as amended, extended or re-enacted from time to time. Any words following the terms "including", "include" or "in particular" are illustrative and do not limit the sense of the preceding words.`,
  ],
];

const confidentiality = (sup: string): Clause => [
  "Confidentiality",
  [
    `Each party shall keep the other party's Confidential Information secret and shall not use it for any purpose other than the performance of its obligations or the exercise of its rights under this Agreement.`,
    `Each party may disclose the other party's Confidential Information to its employees, officers, representatives, subcontractors and advisers who need to know it for the purposes of this Agreement, provided that it ensures that each such recipient is bound by obligations of confidentiality no less protective than those in this clause.`,
    `A party may disclose Confidential Information to the extent required by Applicable Law, by a court of competent jurisdiction or by any governmental or regulatory authority, provided that, to the extent legally permitted, it gives the other party as much notice of the disclosure as possible.`,
    `The obligations in this clause do not apply to information that is or becomes generally available to the public other than through a breach of this Agreement, was lawfully in the possession of the receiving party before disclosure, or is independently developed without use of the disclosing party's Confidential Information.`,
    `On termination or expiry of this Agreement each party shall, at the request of the other, return or destroy the other party's Confidential Information, save that the ${sup} may retain copies required by Applicable Law, which remain subject to this clause.`,
    `The obligations of confidentiality in this clause continue for a period of five (5) years after termination or expiry of this Agreement, and indefinitely in respect of trade secrets.`,
  ],
];

const dataProtection = (sup: string, schedule: number): Clause => [
  "Data protection",
  [
    `The parties acknowledge that, for the purposes of the Data Protection Legislation, the Company is the Controller and the ${sup} is the Processor of any Personal Data processed on behalf of the Company under this Agreement.`,
    `The ${sup} shall process Personal Data only in accordance with the data processing terms in Schedule ${schedule}, which set out the subject matter, duration, nature and purpose of the processing, the types of Personal Data and the categories of Data Subjects, and which meet the requirements of Article 28 of the GDPR.`,
    `The ${sup} shall notify the Company without undue delay, and in any event within twenty-four (24) hours, after becoming aware of a Security Incident, and shall provide all information and cooperation reasonably required by the Company to meet its obligations under the Data Protection Legislation.`,
    `The ${sup} shall not transfer Personal Data outside the European Economic Area without the prior written consent of the Company and, where consent is given, only on the basis of an appropriate transfer mechanism recognised by the Data Protection Legislation.`,
  ],
];

const security = (sup: string): Clause => [
  "Information security",
  [
    `The ${sup} shall maintain an information security management system certified to ISO/IEC 27001, or an equivalent standard approved in writing by the Company, for the duration of this Agreement.`,
    `The ${sup} shall implement appropriate technical and organisational measures to protect Company Data against accidental, unauthorised or unlawful processing, destruction, loss, damage or disclosure, having regard to the state of the art, the cost of implementation and the risks to Data Subjects.`,
    `The ${sup} shall ensure that all Company Data is encrypted in transit using TLS 1.2 or higher and at rest using AES-256 or an equivalent algorithm, and that encryption keys are managed in accordance with Good Industry Practice.`,
    `The ${sup} shall carry out penetration tests of the systems used to provide the services at least once in each calendar year using an independent tester, and shall share a summary of the results and its remediation plan with the Company within thirty (30) days of receiving the report.`,
    `The ${sup} shall maintain role-based access controls, multi-factor authentication for administrative access, and logs of access to Company Data that are retained for at least twelve (12) months and made available to the Company on request.`,
  ],
];

const warranties = (sup: string): Clause => [
  "Warranties",
  [
    `Each party warrants that it has full capacity and authority to enter into and perform this Agreement and that this Agreement is executed by its duly authorised representatives.`,
    `The ${sup} warrants that it will perform its obligations with reasonable skill and care, in accordance with Good Industry Practice and Applicable Law, and using appropriately experienced, qualified and trained personnel.`,
    `The ${sup} warrants that the services and any deliverables will not, when used in accordance with this Agreement, infringe the Intellectual Property Rights of any third party.`,
    `The ${sup} warrants that it will not introduce into the Company's systems any virus, malware, time bomb, trojan horse or other harmful code, and that it will use up-to-date industry-standard tools to detect and prevent such code.`,
    `Except as expressly stated in this Agreement, all warranties, conditions and other terms implied by statute or common law are, to the fullest extent permitted by law, excluded from this Agreement.`,
  ],
];

const indemnities = (sup: string): Clause => [
  "Indemnities",
  [
    `The ${sup} shall indemnify the Company against all losses, damages, costs and expenses, including reasonable legal fees, arising out of any claim that the Company's use of the services or deliverables in accordance with this Agreement infringes the Intellectual Property Rights of a third party.`,
    `The indemnity in the previous paragraph does not apply to the extent a claim arises from modification of the deliverables by the Company without the ${sup}'s consent or from the combination of the deliverables with items not supplied or approved by the ${sup}.`,
    `A party seeking an indemnity shall notify the other party of the claim promptly, shall not make any admission without the other party's consent, and shall give the other party conduct of the defence and reasonable assistance at the other party's expense.`,
    `If an infringement claim is made or is likely to be made, the ${sup} may at its own cost procure the right for the Company to continue using the affected item, or modify or replace it so that it is no longer infringing without any reduction in functionality.`,
  ],
];

const liability = (sup: string): Clause => [
  "Limitation of liability",
  [
    `Nothing in this Agreement limits or excludes liability for death or personal injury caused by negligence, for fraud or fraudulent misrepresentation, for wilful misconduct or gross negligence, or for any other liability that cannot be limited or excluded by Applicable Law.`,
    `Subject to the previous paragraph, each party's total aggregate liability arising out of or in connection with this Agreement, whether in contract, tort (including negligence), breach of statutory duty or otherwise, is limited to the Charges paid or payable by the Company in the twelve (12) months immediately preceding the event giving rise to the claim.`,
    `Neither party is liable for any loss of profits, loss of business, loss of goodwill or any indirect or consequential loss, save that the Company's losses arising from the ${sup}'s breach of the data protection or confidentiality clauses are recoverable as direct losses within the limit set out above.`,
    `The limitation in this clause applies to the aggregate of all claims and is not reset by the renewal of this Agreement or by the entry into of any statement of work.`,
  ],
];

const forceMajeure: Clause = [
  "Force majeure",
  [
    `Neither party is in breach of this Agreement nor liable for delay in performing its obligations if the delay or failure results from events, circumstances or causes beyond its reasonable control, including acts of God, flood, fire, epidemic, war, terrorist attack, civil commotion, or failure of a utility service, but excluding strikes of the affected party's own workforce.`,
    `The affected party shall promptly notify the other party of the force majeure event and its expected duration and shall use all reasonable endeavours to mitigate its effect. The time for performance is extended by a period equivalent to the period during which performance is prevented.`,
    `If the period of delay or non-performance continues for sixty (60) days, the party not affected may terminate this Agreement by giving fourteen (14) days' written notice to the affected party.`,
  ],
];

const compliance = (sup: string): Clause => [
  "Anti-bribery, sanctions and modern slavery",
  [
    `Each party shall comply with all Applicable Law relating to anti-bribery and anti-corruption, including the Polish Criminal Code and, where applicable, the UK Bribery Act 2010 and the US Foreign Corrupt Practices Act, and shall maintain adequate procedures to prevent bribery by persons associated with it.`,
    `The ${sup} warrants that neither it nor any of its Affiliates, directors or officers is the subject of sanctions administered by the European Union, the United Nations, the United Kingdom or the United States, and shall notify the Company immediately if this changes.`,
    `The ${sup} shall take reasonable steps to ensure that there is no slavery, servitude, forced labour or human trafficking in its business or its supply chains, and shall provide information on the steps taken on the Company's reasonable request.`,
  ],
];

const auditRights = (sup: string): Clause => [
  "Records and audit",
  [
    `The ${sup} shall keep complete and accurate records relating to the services, the Charges and its compliance with this Agreement for at least six (6) years after termination or expiry.`,
    `The Company, or an independent auditor appointed by it and bound by confidentiality obligations, may audit the ${sup}'s compliance with this Agreement on giving at least ten (10) Business Days' notice, no more than once in any twelve (12) month period save where an audit is required by a regulator or follows a Security Incident.`,
    `The ${sup} shall give the auditor reasonable access to its premises, systems, records and personnel and shall promptly remedy any non-compliance identified by the audit. If an audit reveals an overcharge of more than five per cent, the ${sup} shall bear the reasonable cost of the audit.`,
  ],
];

const boilerplate = (sup: string, lawClause: string, disputesClause: string): Clause[] => [
  [
    "Assignment and subcontracting",
    [
      `The ${sup} shall not assign, transfer, subcontract or deal in any other manner with any of its rights or obligations under this Agreement without the Company's prior written consent, which shall not be unreasonably withheld.`,
      `The ${sup} remains responsible for all acts and omissions of its subcontractors as if they were its own and shall ensure that each subcontract contains obligations equivalent to those in this Agreement regarding confidentiality, data protection and information security.`,
      `The Company may assign this Agreement to any of its Affiliates or to a successor to all or substantially all of its business on written notice to the ${sup}.`,
    ],
  ],
  [
    "Notices",
    [
      `Any notice under this Agreement shall be in writing and delivered by hand, sent by registered post or courier to the address of the relevant party set out at the beginning of this Agreement, or sent by email to the address notified by the relevant party for that purpose.`,
      `A notice is deemed received, if delivered by hand, at the time of delivery; if sent by registered post or courier, on the third Business Day after posting; and if sent by email, at the time of transmission, provided that no notice of non-delivery is received.`,
      `This clause does not apply to the service of proceedings or other documents in any legal action or, where applicable, any arbitration.`,
    ],
  ],
  [
    "General",
    [
      `This Agreement constitutes the entire agreement between the parties and supersedes all previous agreements, promises, assurances and understandings between them relating to its subject matter.`,
      `No variation of this Agreement is effective unless it is in writing and signed by the parties or their authorised representatives.`,
      `A failure or delay by a party to exercise any right or remedy does not constitute a waiver of that or any other right or remedy. If any provision of this Agreement is found invalid or unenforceable, it shall be deemed modified to the minimum extent necessary to make it valid, and the remaining provisions are not affected.`,
      `Nothing in this Agreement creates a partnership, joint venture or agency between the parties. A person who is not a party to this Agreement has no right to enforce any of its terms.`,
      `This Agreement may be executed in any number of counterparts, each of which is an original and all of which together constitute one agreement. Electronic signatures are valid and binding.`,
    ],
  ],
  ["Governing law", [lawClause]],
  [
    "Dispute resolution",
    [
      `The parties shall attempt in good faith to resolve any dispute through their respective relationship managers and, failing resolution within twenty (20) Business Days, through their senior executives.`,
      disputesClause,
    ],
  ],
];

const signatureBlock = (counterparty: string, name: string, title: string) => `## Signatures

Signed by the authorised representatives of the parties on the dates written below.

For Northwind Analytics sp. z o.o.:
Name: Anna Kowalska
Title: Chief Executive Officer
Date: ______________
Signature: ______________________

For ${counterparty}:
Name: ${name}
Title: ${title}
Date: ______________
Signature: ______________________`;

const extraClauses = (sup: string): Clause[] => [
  [
    "Business continuity and disaster recovery",
    [
      `The ${sup} shall maintain a business continuity and disaster recovery plan that enables it to continue providing the services, or to restore them within the recovery time objective of four (4) hours and the recovery point objective of one (1) hour, following a disruptive event.`,
      `The ${sup} shall test the plan at least once in each calendar year, including a full failover test of production systems, and shall provide the Company with a written summary of the test results, any gaps identified and the actions taken to close them.`,
      `The ${sup} shall invoke the plan promptly on the occurrence of a disruptive event and shall keep the Company informed of progress at intervals of no more than four (4) hours until the services are fully restored.`,
      `The existence of a force majeure event does not relieve the ${sup} of its obligation to implement the plan, and the ${sup} may rely on force majeure only to the extent that a properly implemented plan would not have prevented or mitigated the effect of the event.`,
    ],
  ],
  [
    "Governance and reporting",
    [
      `The parties shall hold an operational review each month, attended by their relationship and contract managers, to review performance against the service levels, open incidents, risks, changes and forecast demand.`,
      `The parties shall hold a strategic review each quarter, attended by a senior executive of each party, to review the overall relationship, the roadmap, commercial matters and any escalated issues.`,
      `The ${sup} shall prepare and circulate an agenda and a written performance report at least three (3) Business Days before each review, and minutes recording decisions and actions within three (3) Business Days after it.`,
      `Each party shall ensure that its representatives at the reviews have the authority to make decisions on the matters on the agenda. Decisions that vary this Agreement take effect only through the change control procedure.`,
    ],
  ],
  [
    "Continuous improvement and benchmarking",
    [
      `The ${sup} shall propose at least twice in each year ways to improve the quality, efficiency or cost of the services, including through new technology, automation and changes in working practices, together with an estimate of the benefits and the investment required.`,
      `The Company may, not more than once in any twenty-four (24) month period, appoint an independent benchmarker to compare the Charges and service levels with those of comparable services provided by other leading suppliers.`,
      `If the benchmark shows that the Charges exceed the upper quartile of the comparison group by more than five per cent, the parties shall negotiate in good faith an adjustment to the Charges to bring them within that range.`,
    ],
  ],
  [
    "Non-solicitation",
    [
      `During the term of this Agreement and for twelve (12) months after its termination or expiry, neither party shall, without the other party's prior written consent, directly or indirectly solicit for employment any person employed by the other party who was materially involved in the services in the preceding twelve (12) months.`,
      `The restriction in the previous paragraph does not prevent either party from employing a person who responds to a general advertisement not targeted at the other party's personnel, or who approaches it on their own initiative.`,
    ],
  ],
  [
    "Publicity",
    [
      `Neither party shall make any public announcement or issue any press release concerning this Agreement or the relationship between the parties without the prior written approval of the other party, except as required by Applicable Law or the rules of a stock exchange.`,
      `The ${sup} shall not use the name, trade marks or logos of the Company or its Affiliates in any marketing material, customer list or case study without the Company's prior written consent, which may be withdrawn at any time.`,
    ],
  ],
  [
    "Conflicts of interest",
    [
      `The ${sup} shall take appropriate steps to ensure that neither it nor its personnel is placed in a position where there is or may be an actual or potential conflict between their interests and the interests of the Company in the performance of this Agreement.`,
      `The ${sup} shall promptly notify the Company in writing of any actual or potential conflict of interest as soon as it becomes aware of it, and shall take such steps as the Company reasonably requires to remove or manage the conflict.`,
    ],
  ],
  [
    "Environmental and social responsibility",
    [
      `The ${sup} shall comply with the Company's supplier code of conduct as notified to it from time to time, including its requirements on environmental management, health and safety, diversity and fair working conditions.`,
      `The ${sup} shall report annually on the energy consumption and estimated greenhouse gas emissions attributable to the services, using a recognised methodology, and shall cooperate with reasonable requests from the Company for information needed for its own sustainability reporting.`,
      `The ${sup} shall use reasonable endeavours to host the services in data centres powered by renewable energy and to reduce the environmental impact of the services over the term of this Agreement.`,
    ],
  ],
];

// ---------------------------------------------------------------------------
// Long MSA, shared by two fixtures that differ only in Schedules 2 and 4.
// ---------------------------------------------------------------------------

const workstreams = [
  [
    "WS-01",
    "Data platform discovery",
    "Inventory of existing data sources, pipelines and consumers; target architecture options with costs and risks",
  ],
  [
    "WS-02",
    "Ingestion framework",
    "Reusable ingestion templates for batch and streaming sources with schema validation and dead-letter handling",
  ],
  ["WS-03", "Warehouse modelling", "Dimensional model for sales, finance and operations domains with documented conformed dimensions"],
  ["WS-04", "Data quality", "Automated quality rules, anomaly detection and a quality dashboard with ownership per dataset"],
  ["WS-05", "Metadata and lineage", "Catalogue integration, column-level lineage capture and business glossary alignment"],
  ["WS-06", "Access management", "Role-based access to datasets aligned with the Company's identity provider and approval workflow"],
  ["WS-07", "Reporting migration", "Migration of 140 legacy reports to the new semantic layer with reconciliation evidence"],
  ["WS-08", "Machine learning platform", "Feature store, experiment tracking and model deployment pipeline for the analytics team"],
  ["WS-09", "Cost management", "Tagging standards, cost dashboards and monthly optimisation recommendations for cloud resources"],
  ["WS-10", "Observability", "Pipeline monitoring, alerting runbooks and on-call handover to the Company's operations team"],
  ["WS-11", "Security hardening", "Network segmentation, secrets management and vulnerability remediation for platform components"],
  ["WS-12", "Knowledge transfer", "Training curriculum, recorded sessions and pairing with Company engineers before handover"],
];

function longMsa(p: {
  supplier: string;
  supplierShort: string;
  signatory: [string, string];
  paymentDays: string;
  insuranceAmount: string;
}): string {
  const sup = "Supplier";
  const body: Clause[] = [
    definitions(sup, [
      `"Deliverables" means all documents, software, data models, reports and other materials created by or on behalf of the Supplier for the Company in the course of providing the Services.`,
      `"Services" means the data engineering, consulting and support services described in Schedule 1 and in each Statement of Work.`,
      `"Statement of Work" means a document substantially in the form set out in Schedule 7, signed by both parties, describing specific Services, Deliverables, milestones and Charges.`,
      `"Service Levels" means the service levels set out in Schedule 3.`,
    ]),
    [
      "Scope and statements of work",
      [
        `The Supplier shall provide the Services and the Deliverables to the Company in accordance with this Agreement and each Statement of Work.`,
        `Each Statement of Work forms a separate contract incorporating the terms of this Agreement. In the event of conflict, the body of this Agreement prevails over the schedules, and the schedules prevail over any Statement of Work, unless the Statement of Work expressly states that it overrides a specific provision.`,
        `The Company is not obliged to order any minimum volume of Services. The Supplier shall not start work under a Statement of Work until it has been signed by both parties.`,
        `The Supplier shall provide the Services from locations within the European Economic Area, unless the Company has agreed otherwise in writing.`,
      ],
    ],
    [
      "Supplier personnel",
      [
        `The Supplier shall appoint a relationship manager with authority to act on its behalf in all matters relating to this Agreement and shall notify the Company of any change in that appointment.`,
        `The Supplier shall ensure that key personnel named in a Statement of Work are not removed from the Services without the Company's prior written consent, except in cases of illness, resignation or termination of employment.`,
        `The Supplier shall ensure that its personnel comply with the Company's site rules, information security policies and code of conduct as notified to the Supplier from time to time.`,
        `The Company may require the Supplier to remove from the Services any individual whose conduct or performance the Company reasonably considers unsatisfactory, and the Supplier shall promptly provide a suitably qualified replacement at no additional cost.`,
        `The Supplier is solely responsible for the remuneration, taxes and social security contributions of its personnel and shall indemnify the Company against any claim that any of its personnel is an employee of the Company.`,
      ],
    ],
    [
      "Company obligations",
      [
        `The Company shall provide the Supplier with timely access to its premises, systems, data and personnel as reasonably required for the Services and as specified in the relevant Statement of Work.`,
        `The Company shall appoint a contract manager who will be the Supplier's principal point of contact for the Services and who has authority to make decisions on the Company's behalf.`,
        `If the Supplier's performance is prevented or delayed by an act or omission of the Company, the Supplier shall notify the Company promptly and is entitled to a reasonable extension of time, provided that it has used reasonable endeavours to mitigate the effect of the delay.`,
      ],
    ],
    [
      "Change control",
      [
        `Either party may request a change to the Services or to a Statement of Work by submitting a written change request describing the change and the reasons for it.`,
        `Within ten (10) Business Days of receiving or submitting a change request, the Supplier shall provide a change proposal setting out the impact on the Services, timetable, Charges and any other terms.`,
        `No change is effective until a change note has been signed by both parties. Until then, the Supplier shall continue to perform the Services as if the change had not been requested.`,
      ],
    ],
    [
      "Acceptance",
      [
        `Each Deliverable shall be subject to acceptance testing against the acceptance criteria set out in the relevant Statement of Work.`,
        `The Company shall notify the Supplier within ten (10) Business Days of delivery whether a Deliverable passes or fails the acceptance tests. If a Deliverable fails, the Supplier shall remedy the defects and resubmit it within ten (10) Business Days.`,
        `If a Deliverable fails acceptance for a second time, the Company may reject it and recover any Charges paid for it, or accept it subject to a reasonable reduction in the Charges.`,
      ],
    ],
    [
      "Charges and payment",
      [
        `In consideration of the Services the Company shall pay the Charges set out in Schedule 2 and in each Statement of Work. The Charges are exclusive of VAT, which the Company shall pay in addition on receipt of a valid VAT invoice.`,
        `The Supplier shall invoice the Company monthly in arrears for Services performed in the previous month, unless a Statement of Work provides for milestone payments. Each invoice shall include the purchase order number and a breakdown of time and expenses.`,
        `The Company shall pay each valid and undisputed invoice within the period set out in Schedule 2.`,
        `If the Company disputes an invoice in good faith, it shall notify the Supplier within ten (10) Business Days of receipt and pay the undisputed part. The parties shall resolve the dispute in accordance with the dispute resolution clause.`,
        `Expenses are payable only if they are approved in writing by the Company in advance and comply with the Company's travel and expenses policy.`,
      ],
    ],
    [
      "Service levels",
      [
        `The Supplier shall meet or exceed the Service Levels. If the Supplier fails to meet a Service Level, it shall promptly investigate the cause, report it to the Company and implement a remediation plan.`,
        `Service credits set out in Schedule 3 are a price adjustment reflecting the reduced value of the Services and are without prejudice to the Company's other rights and remedies.`,
        `If the Supplier fails to meet the same critical Service Level in three (3) consecutive months, the Company may terminate the affected Statement of Work with immediate effect by written notice.`,
      ],
    ],
    confidentiality(sup),
    [
      "Intellectual property",
      [
        `All Intellectual Property Rights in the Deliverables created by or on behalf of the Supplier under this Agreement are assigned to the Company on creation, with full title guarantee, in all fields of use known at the date of this Agreement. The Supplier shall sign any document and do any act required to perfect that assignment.`,
        `The Supplier retains ownership of its pre-existing materials and tools. To the extent any pre-existing materials are incorporated into a Deliverable, the Supplier grants the Company a perpetual, irrevocable, royalty-free, non-exclusive licence to use, copy and modify them as part of that Deliverable.`,
        `The Supplier shall procure that its personnel waive, to the extent permitted by law, any moral rights in the Deliverables, and undertake not to exercise such rights against the Company.`,
        `Company Data and all Intellectual Property Rights in it remain the property of the Company. The Supplier may use Company Data only to provide the Services.`,
      ],
    ],
    dataProtection(sup, 5),
    security(sup),
    warranties(sup),
    indemnities(sup),
    liability(sup),
    [
      "Insurance",
      [
        `The Supplier shall maintain, with a reputable insurer, the insurance cover described in Schedule 4 for the duration of this Agreement and for six (6) years after its termination or expiry.`,
        `The Supplier shall provide the Company with certificates of insurance on request and shall notify the Company promptly of any cancellation or material change in its insurance cover.`,
      ],
    ],
    [
      "Term",
      [
        `This Agreement starts on the Effective Date and continues for an initial term of three (3) years.`,
        `After the initial term, this Agreement ends automatically unless the parties agree in writing, no later than sixty (60) days before its expiry, to extend it for a further period.`,
        `The expiry of this Agreement does not affect any Statement of Work that is in progress, which continues on the terms of this Agreement until its completion or earlier termination.`,
      ],
    ],
    [
      "Termination",
      [
        `Either party may terminate this Agreement or any Statement of Work for convenience by giving the other party at least ninety (90) days' written notice.`,
        `Either party may terminate this Agreement with immediate effect by written notice if the other party commits a material breach that is irremediable or, if remediable, is not remedied within thirty (30) days of written notice requiring it to be remedied.`,
        `Either party may terminate this Agreement with immediate effect by written notice if the other party becomes insolvent, enters into restructuring or bankruptcy proceedings, or ceases to carry on business.`,
        `The Company may terminate this Agreement with immediate effect if the Supplier undergoes a change of control in favour of a competitor of the Company.`,
      ],
    ],
    [
      "Consequences of termination",
      [
        `On termination or expiry the Supplier shall promptly return all Company Data and Company property in its possession, in the format reasonably requested by the Company, and then securely delete all copies, providing a certificate of deletion signed by an officer of the Supplier.`,
        `The Company shall pay the Charges for Services properly performed up to the date of termination. Where the Company terminates for convenience, it shall also reimburse the Supplier's reasonable and documented costs of non-cancellable commitments made for the Services.`,
        `Termination does not affect any rights, remedies, obligations or liabilities of the parties accrued up to the date of termination, and clauses that expressly or by implication survive termination continue in force.`,
        `The Supplier shall provide the exit assistance described in Schedule 6 for up to six (6) months after termination or expiry.`,
      ],
    ],
    [
      "Step-in rights",
      [
        `If the Supplier fails to meet a critical Service Level for two (2) consecutive months, suffers a Security Incident affecting Company Data, or is subject to a force majeure event lasting more than ten (10) Business Days, the Company may take control of the affected Services itself or through a third party.`,
        `The Company shall give the Supplier at least five (5) Business Days' written notice of its intention to step in, save in an emergency, and shall step in only for as long as reasonably necessary to address the circumstances giving rise to the step-in.`,
        `During step-in the Supplier shall cooperate fully with the Company and its nominee, provide access to the relevant systems, data and personnel, and continue to perform any Services not affected by the step-in.`,
        `The Supplier shall bear the reasonable costs of step-in where it results from the Supplier's breach, and the Company shall not pay the Charges for the affected Services for the duration of the step-in.`,
      ],
    ],
    ...extraClauses(sup),
    forceMajeure,
    compliance(sup),
    auditRights(sup),
    ...boilerplate(
      sup,
      "This Agreement and any dispute or claim arising out of or in connection with it, including non-contractual disputes or claims, is governed by and construed in accordance with the laws of Poland.",
      "Any dispute not resolved under the previous paragraph shall be finally settled by arbitration under the Rules of the Court of Arbitration at the Polish Chamber of Commerce in Warsaw. The seat of arbitration is Warsaw, the tribunal consists of three arbitrators, and the language of the proceedings is English.",
    ),
  ];

  const schedule1 = schedule(
    1,
    "Services description",
    [
      "The Services consist of the workstreams listed below. Detailed scope, milestones and acceptance criteria for each workstream are agreed in the relevant Statement of Work.",
      table(
        ["Ref", "Workstream", "Scope"],
        workstreams.map((w) => [...w]),
      ),
      scheduleClauses(1, [
        "The Supplier shall run each workstream using two-week iterations with a demonstration to the Company's product owner at the end of each iteration.",
        "The Supplier shall maintain a single backlog for all workstreams, prioritised jointly with the Company, and shall publish a weekly status report covering progress, risks, issues and forecast effort.",
        "All code produced under the Services shall be stored in the Company's source control system, reviewed by at least one other engineer before merging, and accompanied by automated tests with at least eighty per cent line coverage for new modules.",
        "The Supplier shall document architecture decisions in the Company's decision register and keep operational runbooks up to date for every component it builds or modifies.",
        "The Supplier shall provide second-line support for components it has delivered during business hours (08:00 to 18:00 Warsaw time) for the duration of the relevant Statement of Work.",
      ]),
    ].join("\n\n"),
  );

  const schedule2 = schedule(
    2,
    "Charges and payment terms",
    [
      "The Services are charged on a time and materials basis at the day rates below unless a Statement of Work specifies a fixed price.",
      table(
        ["Role", "Day rate (EUR)", "Minimum notice to staff"],
        [
          ["Principal architect", "1,450", "20 Business Days"],
          ["Senior data engineer", "1,050", "15 Business Days"],
          ["Data engineer", "820", "10 Business Days"],
          ["Analytics engineer", "780", "10 Business Days"],
          ["Machine learning engineer", "1,120", "15 Business Days"],
          ["Delivery manager", "950", "10 Business Days"],
          ["Quality analyst", "690", "10 Business Days"],
        ],
      ),
      scheduleClauses(2, [
        "A day means eight (8) hours of work. Time is recorded in the Company's timesheet tool in half-day units and approved by the Company's contract manager each week.",
        "Day rates are fixed for the first twelve (12) months after the Effective Date. Thereafter the Supplier may increase them once in each year by no more than the annual change in the harmonised index of consumer prices for the euro area published by Eurostat.",
        "Volume discount: where total Charges invoiced in a calendar year exceed EUR 1,500,000, a discount of four per cent applies to Charges above that amount and is credited against the next invoice.",
        `Payment terms: the Company shall pay each valid and undisputed invoice within ${p.paymentDays} of receipt of the invoice.`,
        "Invoices shall be sent electronically to the Company's accounts payable address and shall be issued in euro. Payments are made by bank transfer to the account stated on the invoice.",
      ]),
    ].join("\n\n"),
  );

  const schedule3 = schedule(
    3,
    "Service levels and service credits",
    [
      table(
        ["Service level", "Target", "Measurement", "Service credit"],
        [
          [
            "Production pipeline availability",
            "99.5% monthly",
            "Minutes of successful scheduled runs",
            "5% of monthly Charges per 0.5% below target",
          ],
          ["P1 incident response", "30 minutes", "Time from alert to acknowledgement", "2% of monthly Charges per breach"],
          ["P1 incident resolution", "4 hours", "Time from alert to restoration", "3% of monthly Charges per breach"],
          ["P2 incident resolution", "1 Business Day", "Time from ticket to fix", "1% of monthly Charges per breach"],
          ["Report delivery", "By 07:00 each Business Day", "Timestamp of refreshed dashboards", "1% of monthly Charges per late day"],
          ["Change success rate", "95% monthly", "Changes without rollback", "2% of monthly Charges if missed"],
        ],
      ),
      scheduleClauses(3, [
        "Service levels are measured monthly by the Supplier using tooling agreed with the Company and reported within five (5) Business Days after the end of each month.",
        "Total service credits in any month shall not exceed fifteen per cent of the Charges for that month.",
        "Service levels do not apply to failures caused by the Company's systems, by third-party services outside the Supplier's control, or by planned maintenance notified at least five (5) Business Days in advance.",
      ]),
    ].join("\n\n"),
  );

  const schedule4 = schedule(
    4,
    "Insurance",
    scheduleClauses(4, [
      `Professional indemnity insurance with a limit of indemnity of not less than ${p.insuranceAmount} for each and every claim.`,
      "Public and products liability insurance with a limit of indemnity of not less than EUR 5,000,000 for each occurrence.",
      "Cyber liability insurance, including cover for data breach response costs and regulatory defence, with a limit of not less than EUR 3,000,000 in the aggregate.",
      "Employer's liability insurance as required by Applicable Law in each country where the Supplier's personnel are employed.",
    ]),
  );

  const schedule5 = schedule(
    5,
    "Data processing terms",
    scheduleClauses(5, [
      "Subject matter and duration: the processing of Personal Data necessary for the Services, for the duration of this Agreement and any exit period.",
      "Nature and purpose: storage, transformation, analysis and reporting of Company Data on the Company's data platform.",
      "Types of Personal Data: identification and contact data, employment data of Company staff, customer account data and transaction data.",
      "Categories of Data Subjects: employees and contractors of the Company, and customers and prospective customers of the Company.",
      "The Supplier shall process Personal Data only on the documented instructions of the Company, ensure that persons authorised to process it are bound by confidentiality, implement the security measures required by Article 32 of the GDPR, and engage sub-processors only with the Company's prior written authorisation and on terms no less protective than these.",
      "The Supplier shall assist the Company in responding to requests from Data Subjects and in meeting its obligations under Articles 32 to 36 of the GDPR, and shall make available all information necessary to demonstrate compliance with Article 28 of the GDPR, including by allowing and contributing to audits.",
      "At the end of the provision of the Services, the Supplier shall, at the Company's choice, delete or return all Personal Data and delete existing copies unless Applicable Law requires their storage.",
    ]),
  );

  const schedule6 = schedule(
    6,
    "Exit management",
    scheduleClauses(6, [
      "Within three (3) months of the Effective Date the Supplier shall deliver an exit plan describing how the Services will be transferred to the Company or a replacement supplier with minimal disruption.",
      "The exit plan shall include an inventory of assets, data and documentation, a handover timetable, knowledge transfer sessions, and the roles and responsibilities of each party during exit.",
      "The Supplier shall review and update the exit plan annually and within one (1) month of any material change to the Services.",
      "During the exit period the Supplier shall continue to provide the Services to the Service Levels and shall cooperate fully with the Company and any replacement supplier.",
      "Exit assistance is charged at the day rates in Schedule 2, save that no Charges are payable for exit assistance where the Company has terminated for the Supplier's material breach.",
    ]),
  );

  const schedule7 = schedule(
    7,
    "Form of statement of work",
    scheduleClauses(7, [
      "Each Statement of Work shall contain: a unique reference number; a description of the Services and Deliverables; milestones and delivery dates; acceptance criteria; key personnel; Charges and payment milestones; dependencies on the Company; and any specific risks and assumptions.",
      "A Statement of Work may not vary the provisions of this Agreement on liability, data protection, confidentiality, intellectual property, governing law or dispute resolution.",
      "Each Statement of Work shall be signed by authorised representatives of both parties and is effective from the later of the dates of signature.",
    ]),
  );

  return [
    "# Master Services Agreement",
    `This Master Services Agreement is made on the date of the last signature below between ${COMPANY} (the "Company"), and ${p.supplier} (the "Supplier"), each a "party" and together the "parties".`,
    `Background: the Company wishes to modernise its data platform and analytics capabilities, and the Supplier has agreed to provide data engineering and consulting services on the terms of this Agreement. ${p.supplierShort} has represented that it has the expertise, personnel and certifications needed to do so.`,
    clauses(body),
    signatureBlock(p.supplier, p.signatory[0], p.signatory[1]),
    schedule1,
    schedule2,
    schedule3,
    schedule4,
    schedule5,
    schedule6,
    schedule7,
  ].join("\n\n");
}

// ---------------------------------------------------------------------------
// Long SaaS agreement with an override deep in the special conditions.
// ---------------------------------------------------------------------------

const modules = [
  ["Core analytics", "Dashboards, ad hoc queries and scheduled reports for up to 250 named users", "Included"],
  ["Data connectors", "Managed connectors for 40 sources including ERP, CRM, advertising and payment systems", "Included"],
  ["Embedded analytics", "White-labelled dashboards embedded in the Company's customer portal", "Add-on"],
  ["Governance pack", "Row-level security, audit trail export and data retention policies", "Included"],
  ["Forecasting", "Time-series forecasting with automated backtesting and explainability reports", "Add-on"],
  ["Premium support", "24/7 support with a named technical account manager", "Add-on"],
  ["Sandbox environment", "Isolated non-production environment refreshed weekly with masked data", "Included"],
  ["API access", "REST and SQL interfaces with 50 million calls per month", "Included"],
];

function longSaas(): string {
  const sup = "Provider";
  const body: Clause[] = [
    definitions(sup, [
      `"Authorised Users" means employees and contractors of the Company and its Affiliates who are authorised by the Company to use the Platform.`,
      `"Documentation" means the user guides, technical specifications and help centre articles for the Platform made available by the Provider, as updated from time to time.`,
      `"Minimum Commitment Period" has the meaning given in Schedule 6.`,
      `"Platform" means the Provider's hosted analytics platform known as CloudVista Enterprise, including the modules listed in Schedule 1 and all updates and upgrades made available during the Subscription Term.`,
      `"Subscription Term" means the initial term and any renewal term under the term clause.`,
    ]),
    [
      "Subscription and access",
      [
        `Subject to the Company paying the Charges, the Provider grants the Company and its Authorised Users a non-exclusive, non-transferable right during the Subscription Term to access and use the Platform and the Documentation for the internal business purposes of the Company and its Affiliates.`,
        `The Company may increase the number of Authorised Users or add modules at any time by written order at the prices in Schedule 2, pro-rated for the remainder of the current subscription year.`,
        `The Company shall not, and shall ensure that Authorised Users do not, resell the Platform, attempt to reverse engineer it except as permitted by Applicable Law, or use it to build a competing product.`,
        `The Provider may suspend access of an individual Authorised User who breaches the acceptable use policy in the Documentation, after notifying the Company and giving it a reasonable opportunity to address the breach.`,
      ],
    ],
    [
      "Provider obligations",
      [
        `The Provider shall provide the Platform substantially in accordance with the Documentation and the service levels in Schedule 3, using Good Industry Practice.`,
        `The Provider shall host the Platform and all Company Data in data centres located in the European Union, currently in Frankfurt and Amsterdam, and shall not change the hosting location without the Company's prior written consent.`,
        `The Provider may update the Platform from time to time, provided that no update materially reduces the functionality, security or performance of the Platform. The Provider shall give at least thirty (30) days' notice of any change that requires action by the Company.`,
        `The Provider shall provide the support services described in Schedule 4.`,
      ],
    ],
    [
      "Company obligations",
      [
        `The Company is responsible for the accuracy and legality of the Company Data it uploads and for the acts and omissions of its Authorised Users.`,
        `The Company shall keep login credentials confidential, enable multi-factor authentication for all Authorised Users, and notify the Provider promptly of any suspected unauthorised use of the Platform.`,
        `The Company shall maintain its own network connectivity and hardware as reasonably required to access the Platform in accordance with the Documentation.`,
      ],
    ],
    [
      "Charges and payment",
      [
        `The Company shall pay the subscription fees and any other Charges set out in Schedule 2. Subscription fees are invoiced annually in advance at the start of each subscription year.`,
        `Invoices are payable within thirty (30) days of receipt. All amounts are exclusive of VAT, which is payable in addition.`,
        `If the Company fails to pay an undisputed invoice by its due date, the Provider may charge statutory interest for late payment in commercial transactions and, after giving thirty (30) days' further written notice, suspend access to the Platform until payment is made.`,
        `The Provider may increase the subscription fees on renewal by giving at least ninety (90) days' written notice before the end of the current term, provided that any increase does not exceed five per cent per year.`,
      ],
    ],
    [
      "Service levels and support",
      [
        `The Provider shall make the Platform available in accordance with the availability commitment in Schedule 3 and shall pay the service credits set out there if it fails to do so.`,
        `Service credits are the Company's sole financial remedy for failure to meet the availability commitment, save that repeated failure constitutes a material breach as described in Schedule 3.`,
        `Planned maintenance shall take place outside 07:00 to 20:00 Warsaw time on Business Days and shall not exceed eight (8) hours in any calendar month.`,
      ],
    ],
    confidentiality(sup),
    [
      "Intellectual property",
      [
        `The Provider and its licensors own all Intellectual Property Rights in the Platform and the Documentation. Except for the rights expressly granted in this Agreement, no rights are transferred to the Company.`,
        `The Company owns all Intellectual Property Rights in Company Data and in reports and dashboards created by Authorised Users using the Platform.`,
        `The Company grants the Provider a non-exclusive licence to use Company Data during the Subscription Term solely to provide the Platform and support services.`,
        `The Provider may use anonymised and aggregated usage statistics that do not identify the Company or any individual to improve the Platform.`,
      ],
    ],
    dataProtection(sup, 5),
    security(sup),
    warranties(sup),
    indemnities(sup),
    liability(sup),
    [
      "Term and renewal",
      [
        `This Agreement starts on the Effective Date and continues for an initial term of twelve (12) months.`,
        `After the initial term this Agreement renews for successive periods of twelve (12) months unless either party gives the other written notice of non-renewal at least sixty (60) days before the end of the then-current term.`,
        `The Provider shall remind the Company in writing of the upcoming renewal date at least ninety (90) days before the end of each term.`,
      ],
    ],
    [
      "Termination",
      [
        `Either party may terminate this Agreement for convenience by giving the other party at least thirty (30) days' written notice. On termination for convenience by the Company, the Provider shall refund any prepaid subscription fees for the period after the termination date.`,
        `Either party may terminate this Agreement with immediate effect by written notice if the other party commits a material breach that is not remedied within thirty (30) days of written notice.`,
        `Either party may terminate this Agreement with immediate effect by written notice if the other party becomes insolvent, enters into restructuring or bankruptcy proceedings, or ceases to carry on business.`,
      ],
    ],
    [
      "Consequences of termination",
      [
        `For thirty (30) days after termination or expiry, the Provider shall allow the Company to export all Company Data in a standard machine-readable format at no additional charge.`,
        `After the export period the Provider shall delete all Company Data from the Platform and its backups within ninety (90) days and confirm the deletion in writing.`,
        `Termination does not affect any rights or remedies accrued before termination, and clauses that by their nature survive termination continue in force.`,
      ],
    ],
    [
      "Continuity of service and escrow",
      [
        `The Provider shall deposit the source code of the Platform, together with build instructions and deployment scripts, with an independent escrow agent approved by the Company, and shall update the deposit within thirty (30) days of each major release.`,
        `The Company may obtain release of the deposit if the Provider becomes insolvent, ceases to maintain the Platform, or fails to remedy a P1 incident within ten (10) Business Days, and may then use the deposit solely to maintain the Platform for its own internal purposes.`,
        `The Provider shall bear the fees of the escrow agent. The Company may require a verification test of the deposit once in each year at the Provider's cost.`,
      ],
    ],
    ...extraClauses(sup),
    forceMajeure,
    compliance(sup),
    auditRights(sup),
    ...boilerplate(
      sup,
      "This Agreement and any non-contractual obligations arising out of or in connection with it are governed by the laws of Poland.",
      "Any dispute not resolved under the previous paragraph shall be submitted to the exclusive jurisdiction of the common courts competent for Warsaw, Poland.",
    ),
  ];

  const schedule1 = schedule(
    1,
    "Platform modules",
    [
      table(
        ["Module", "Description", "Status"],
        modules.map((m) => [...m]),
      ),
      scheduleClauses(1, [
        "Included modules are covered by the base subscription fee. Add-on modules are available at the prices in Schedule 2 and may be added or removed at each renewal.",
        "New modules released during the Subscription Term that replace or materially extend an included module are made available at no additional charge.",
        "The Provider shall give at least twelve (12) months' notice before withdrawing any included module, and shall offer a functionally equivalent replacement.",
      ]),
    ].join("\n\n"),
  );

  const schedule2 = schedule(
    2,
    "Charges",
    [
      table(
        ["Item", "Unit", "Annual price (EUR)"],
        [
          ["Base subscription (250 Authorised Users)", "Per year", "186,000"],
          ["Additional Authorised Users", "Per 25 users", "14,500"],
          ["Embedded analytics", "Per year", "42,000"],
          ["Forecasting", "Per year", "28,000"],
          ["Premium support", "Per year", "24,000"],
          ["Additional API calls", "Per 10 million calls", "3,200"],
        ],
      ),
      scheduleClauses(2, [
        "Prices are fixed for the initial term and are subject to the renewal price clause thereafter.",
        "Add-on modules and additional users ordered during a subscription year are invoiced on the order date, pro-rated to the end of that subscription year, and payable on the same terms as other invoices.",
      ]),
    ].join("\n\n"),
  );

  const schedule3 = schedule(
    3,
    "Availability and service credits",
    [
      table(
        ["Monthly availability", "Service credit (% of monthly fee)"],
        [
          ["99.9% or higher", "0%"],
          ["99.5% to below 99.9%", "5%"],
          ["99.0% to below 99.5%", "10%"],
          ["95.0% to below 99.0%", "20%"],
          ["Below 95.0%", "35%"],
        ],
      ),
      scheduleClauses(3, [
        "Availability is measured each calendar month as the percentage of minutes in which the Platform's production interface responds successfully to synthetic monitoring from two independent locations, excluding planned maintenance.",
        "Availability below 99.0% in any three (3) months within a rolling twelve (12) month period constitutes a material breach that entitles the Company to terminate under the termination clause.",
        "The Provider shall publish availability reports on its status page and send a monthly report to the Company within five (5) Business Days after the end of each month.",
      ]),
    ].join("\n\n"),
  );

  const schedule4 = schedule(
    4,
    "Support services",
    [
      table(
        ["Priority", "Definition", "Response time", "Target resolution"],
        [
          ["P1", "Platform unavailable or data loss", "30 minutes, 24/7", "4 hours"],
          ["P2", "Major function impaired, no workaround", "2 business hours", "1 Business Day"],
          ["P3", "Function impaired, workaround available", "1 Business Day", "5 Business Days"],
          ["P4", "Question or cosmetic issue", "2 Business Days", "Next release"],
        ],
      ),
      scheduleClauses(4, [
        "Support is available by portal, email and telephone. The Company may designate up to ten (10) support contacts.",
        "The Provider shall provide a root cause analysis for every P1 incident within five (5) Business Days of resolution.",
      ]),
    ].join("\n\n"),
  );

  const schedule5 = schedule(
    5,
    "Data processing addendum",
    scheduleClauses(5, [
      "This addendum sets out the terms required by Article 28(3) of the GDPR for the processing of Personal Data by the Provider on behalf of the Company.",
      "Subject matter and duration: hosting and processing of Company Data within the Platform for the Subscription Term and the export period.",
      "Nature and purpose: storage, querying, visualisation and support access to Company Data as instructed by the Company through its use of the Platform.",
      "Types of Personal Data and Data Subjects: contact, account and transaction data of the Company's customers, and identification data of Authorised Users.",
      "The Provider shall process Personal Data only on documented instructions from the Company, ensure the confidentiality of persons authorised to process it, implement the measures required by Article 32 of the GDPR, and assist the Company with Data Subject requests and with its obligations under Articles 32 to 36 of the GDPR.",
      "The Provider may engage the sub-processors listed in its trust centre on the Effective Date. It shall give at least thirty (30) days' notice of any new sub-processor, during which the Company may object on reasonable grounds.",
      "The Provider shall make available to the Company all information necessary to demonstrate compliance with this addendum and allow for audits, including inspections, by the Company or an auditor mandated by it.",
    ]),
  );

  const schedule6 = schedule(
    6,
    "Special conditions",
    scheduleClauses(6, [
      "These special conditions were negotiated in return for the discounted pricing in Schedule 2 and take precedence over the body of this Agreement where they conflict with it.",
      "Minimum Commitment Period means the period of thirty-six (36) months starting on the Effective Date.",
      "Notwithstanding clause 15.1, the Company may not terminate this Agreement for convenience during the Minimum Commitment Period, and any notice of termination for convenience given during that period has no effect.",
      "During the Minimum Commitment Period the Provider shall not increase the subscription fees for the modules and user numbers listed in Schedule 2 on the Effective Date.",
      "The Provider shall provide up to twenty (20) days of onboarding consultancy during the first six (6) months at no additional charge.",
    ]),
  );

  const schedule7 = schedule(
    7,
    "Security requirements",
    [
      "The Provider shall implement and maintain at least the following controls throughout the Subscription Term.",
      table(
        ["Area", "Control", "Evidence"],
        [
          [
            "Governance",
            "Named chief information security officer and documented security policy reviewed annually",
            "Policy and organisation chart",
          ],
          ["Certification", "ISO/IEC 27001 certification covering the Platform and its hosting", "Current certificate"],
          ["Assurance", "SOC 2 Type II report covering security, availability and confidentiality", "Annual report under NDA"],
          ["Personnel", "Background checks for staff with access to Company Data, and annual security training", "Training records"],
          ["Access", "Least-privilege access, quarterly access reviews and multi-factor authentication for all staff", "Review logs"],
          ["Encryption", "TLS 1.2 or higher in transit and AES-256 at rest with keys in a managed key service", "Architecture description"],
          ["Vulnerabilities", "Critical vulnerabilities patched within 7 days and high within 30 days", "Patch reports"],
          ["Testing", "Annual independent penetration test and continuous automated scanning", "Summary report"],
          ["Logging", "Security logs retained for 12 months and monitored by a 24/7 security operations centre", "Monitoring description"],
          ["Backups", "Daily encrypted backups replicated to a second EU region, restore tested quarterly", "Restore test records"],
          ["Development", "Secure development lifecycle with code review, dependency scanning and secrets scanning", "SDLC policy"],
          ["Incidents", "Documented incident response plan tested annually, with customer notification within 24 hours", "Test report"],
        ],
      ),
      scheduleClauses(7, [
        "The Provider shall not materially reduce the level of security provided by these controls during the Subscription Term.",
        "The Provider shall answer the Company's reasonable security questionnaires once in each year and within ten (10) Business Days of any Security Incident.",
        "Where the Provider becomes aware that it cannot meet any control, it shall notify the Company within five (5) Business Days together with a remediation plan and timetable.",
      ]),
    ].join("\n\n"),
  );

  const schedule8 = schedule(
    8,
    "Implementation plan",
    [
      "The Provider shall implement the Platform for the Company in the phases below. Dates are measured from the Effective Date.",
      table(
        ["Phase", "Activities", "Company inputs", "Completion"],
        [
          [
            "1. Mobilisation",
            "Kick-off, project plan, access provisioning, single sign-on configuration",
            "Identity provider details, named project lead",
            "Week 2",
          ],
          [
            "2. Data onboarding",
            "Connector set-up for ERP, CRM and billing systems; initial historical loads",
            "Source system credentials, data owners",
            "Week 6",
          ],
          [
            "3. Modelling",
            "Semantic layer for finance, sales and operations; metric definitions signed off",
            "Metric owners, sample reports",
            "Week 10",
          ],
          [
            "4. Dashboards",
            "Migration of 60 priority dashboards with reconciliation against legacy reports",
            "Report inventory, acceptance testers",
            "Week 14",
          ],
          [
            "5. Embedded analytics",
            "Customer portal integration, theming and row-level security for external users",
            "Portal team, test tenants",
            "Week 18",
          ],
          ["6. Hypercare", "Daily health checks, defect triage and weekly steering meetings", "Support contacts", "Week 22"],
        ],
      ),
      scheduleClauses(8, [
        "Each phase ends with a completion review at which the Company confirms in writing that the exit criteria for the phase are met. The Company shall not unreasonably withhold or delay confirmation.",
        "If the Provider fails to complete a phase within four (4) weeks of its planned completion date for reasons within its control, the Company is entitled to a credit of five per cent of the first-year subscription fee for each further week of delay, up to a maximum of twenty-five per cent.",
        "The Provider shall assign a named implementation manager and a solutions architect for the duration of the implementation, and shall not replace them without the Company's consent except for reasons outside the Provider's control.",
        "The Provider shall deliver administrator training for up to fifteen (15) Company staff and end-user training material in English and Polish before the end of Phase 4.",
        "Implementation risks, issues and decisions shall be recorded in a shared log reviewed at a weekly steering meeting attended by both project leads.",
      ]),
    ].join("\n\n"),
  );

  return [
    "# Enterprise Subscription Agreement",
    `This Enterprise Subscription Agreement is made on the date of the last signature below between ${COMPANY} (the "Company"), and CloudVista GmbH, a company incorporated in Germany with its registered office at Rosenthaler Straße 40, 10178 Berlin, registered with the Charlottenburg local court under HRB 214567 (the "Provider").`,
    "Background: the Provider operates a hosted analytics platform and the Company wishes to subscribe to it for use across its business and its Affiliates on the terms of this Agreement.",
    clauses(body),
    signatureBlock("CloudVista GmbH", "Jonas Richter", "Managing Director"),
    schedule1,
    schedule2,
    schedule3,
    schedule4,
    schedule5,
    schedule6,
    schedule7,
    schedule8,
  ].join("\n\n");
}

export const longAgreementSources = {
  msaDeepMediumIssues: longMsa({
    supplier:
      "Orbital Systems Integration S.A., a company incorporated in Luxembourg with its registered office at 12 rue Eugène Ruppert, L-2453 Luxembourg",
    supplierShort: "Orbital",
    signatory: ["Claire Wagner", "Chief Executive Officer"],
    paymentDays: "seventy-five (75) days",
    insuranceAmount: "EUR 250,000",
  }),
  msaLongCompliant: longMsa({
    supplier: "Lindqvist Data Services AB, a company incorporated in Sweden with its registered office at Kungsgatan 8, 111 43 Stockholm",
    supplierShort: "Lindqvist",
    signatory: ["Erik Lindqvist", "Managing Director"],
    paymentDays: "forty-five (45) days",
    insuranceAmount: "EUR 2,000,000",
  }),
  saasTerminationOverride: longSaas(),
};
